### ISSUE TITLE
Spelling: organization

### ISSUE THREAD

**Issue by luciussilanus** [mine-your-business/myb-nicehash-api#3]
https://github.com/mine-your-business/myb-nicehash-api/blob/795dbad795566b2a1b44ac8137f2fe09eda42898/nicehash/client.py#L82

organisation should be spelled organization.

**Comment by piekstra** [comment]
@luciussilanus technically, both are correct English. With `Organisation` being the British English version of the word but still valid in American English.

I believe the spelling in this instance was copied from an example provided by NiceHash which is currently based out of the British Virgin Islands, a British overseas territory.

That said, my personal preference is to use the `z` in the spelling so if you would like to fork the repo and submit a pull request to change the spelling, I would accept that change.

**Comment by luciussilanus** [comment]
The more you know!
